# 初始版本 20250326
sfr:
  image_info:
    image_size: [400, 400]
    crop_tblr: [0, 0, 0, 0]
    bayer_pattern: "Y"
    image_type: "RAW8"
    sub_black_level: false
    black_level: 64
    
  locate_block:
    max_radius: 250
    bw_mode: "FIX_THRESH"
    apply_hull: true
    bw_thresh: 0.25
    mask_erode_size: [3, 3]
    canny_thresh: [20, 30]
    blur_size: (5, 5)
    n_block: 17
    block_thresh: [750, 1350]
    n_half_block: 0
    half_block_thresh: [0, 0] 
    half_bloack_dist_from_center: [0, 0]
    n_point: 0
    point_thresh: [3, 25]
    point_dist_from_center: [160, 180]
    inner_block_thresh: [0, 0]
    delta_angle: 15
    roi_size: [24, 24]
    debug_flag: false
    clockwise: true
    text_size: 0.3
    thickness: 1
    x_offset: 3
    y_offset: 10
  
  customized_params:
    points_offset_xy: [120, 120]
    points_roi_size: [60, 60]
    image_circle: 200
    fov_design: 100
    fov_ratio: 0.8
  
  select_roi:
    roi_inex: [0,1,2,3,
              4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,
              20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,
              36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,
              52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67
              ]
  
  mtf:
    ny_freq: [2, 4]
    debug_flag: true
    text_value: false
    csv_output: true
